### ISSUE TITLE
Request - Possible to add multiple pihole addresses and multiple domains

### ISSUE THREAD

**Issue by twist3dimages** [fire1ce/pihole-cloudflare-dns-sync#1]
Great job on this, just wanted to see if it was possible to add multiple pihole hosts as variables and if multiple domains could be added. Thanks!

**Comment by fire1ce** [comment]
@twist3dimages first of all thanks. 
About multi pinholes, just run another instants of container with other pi params. 
About multi domain support, i don’t have time in near future to implement this feature. PR are always welcomed.
